In [1]:
import pandas as pd 
df = pd.read_csv('https://raw.githubusercontent.com/ghazafm/SocialMediaSentiment/main/preprocessing/EDA/datasets/anis.csv')
df.head(10)

,Unnamed: 0,Date,User ID,Tweet Count,Tweet Location,Tweet,label,Clean,city
0,1,2023-04-16,771030588.0,30121,"Palmerah, Jakarta",politisi partai gerindra sandiaga uno menjawab...,Positive,politisi partai gerindra sandiaga uno menjawab...,Palmerah
1,2,2023-04-16,380755133.0,230,Jakarta - Utara,lanjut pak anies kita kawal sampai jadi presiden,Positive,lanjut pak kita kawal sampai jadi,Jakarta - Utara
2,5,2023-04-16,634227637.0,5297,"Jawa Barat, Indonesia",kader pdip jadi presiden yang mana menterinya ...,Negative,kader pdip jadi yang mana menterinya impor pangan,Jawa Barat
3,6,2023-04-16,634227637.0,5297,"Jawa Barat, Indonesia",jika tidak ada deklarasi dari partai pendukung...,Positive,jika tidak ada deklarasi dari partai pendukung...,Jawa Barat
4,7,2023-04-16,634227637.0,5297,"Jawa Barat, Indonesia",suara rakyat,Positive,suara rakyat,Jawa Barat
5,8,2023-04-16,171458202.0,35,Tangerang Selatan,amien rais akan pilih prabowo subianto bila an...,Negative,amien rais akan pilih subianto bila gagal jadi...,Tangerang Selatan
6,9,2023-04-16,634227637.0,5297,"Jawa Barat, Indonesia",siapa dulu gunernurnya,Positive,siapa dulu gunernurnya,Jawa Barat
7,10,2023-04-16,634227637.0,5297,"Jawa Barat, Indonesia",kpk bergerak keadilan bagi seluruh rakyat indo...,Negative,kpk bergerak keadilan bagi seluruh rakyat indo...,Jawa Barat
8,11,2023-04-16,634227637.0,5297,"Jawa Barat, Indonesia",anies prabowo,Positive,NaN,Jawa Barat
9,12,2023-04-16,634227637.0,5297,"Jawa Barat, Indonesia",bisa jadi gubernur karena ada partai yang mend...,Negative,bisa jadi gubernur karena ada partai yang mend...,Jawa Barat

In [6]:
df_neg = df[df['label']=='Negative']
df_negative = df[df['label']=='Negative']
df_negative = df_negative.groupby('User ID').size().nlargest(10).reset_index(name='Count')
df_negative = pd.DataFrame(df_negative)
df_negative = pd.merge(df_negative, df_neg, on='User ID')
# 'df_negative.to_csv('anies_negative.csv')'
df_negative['User ID'].value_counts()
df_negative_count = pd.DataFrame(df_negative['User ID'].value_counts())
df_negative_count

              count
User ID
4.858565e+08     52
3.066158e+08     35
3.158832e+09     26
6.342276e+08     14
6.918316e+07      7
6.893055e+07      6
1.812994e+07      5
3.076681e+07      5
4.669304e+07      5
1.996097e+08      5

In [5]:
df_pos = df[df['label']=='Positive']
df_positive = df[df['label']=='Positive']
df_positive = df_positive.groupby('User ID').size().nlargest(10).reset_index(name='Count')
df_positive = pd.DataFrame(df_positive)
df_positive = pd.merge(df_positive, df_pos, on='User ID')
# df_positive.to_csv('anies_positive.csv')
df_positive_count = pd.DataFrame(df_positive['User ID'].value_counts())
df_positive_count

              count
User ID
3.066158e+08    150
4.669304e+07     61
7.563741e+08     24
2.558198e+09     23
2.718336e+09     20
6.918316e+07     18
4.280084e+08     17
1.091492e+08     16
3.158832e+09     14
5.671330e+08     12