In [1]:
import pandas as pd 
df = pd.read_csv('D:\BCC\Projek_Intern\SocialMediaSentiment\preprocessing\EDA\datasets\gabungan.csv')

In [14]:

# Hitung jumlah tweet untuk setiap user
user_tweet_counts = df['User ID'].value_counts()

# Gabungkan jumlah tweet ke DataFrame awal
df_with_counts = df.merge(user_tweet_counts.rename('Count'), left_on='User ID', right_index=True)

# Urutkan berdasarkan jumlah tweet
sorted_df = df_with_counts.sort_values(by='Tweet Count', ascending=False)

# Ambil 10 user teratas beserta tweetnya
top_10_users_with_tweets = pd.DataFrame(sorted_df.groupby('User ID').head(10))

# Tampilkan hasil
top_10_users_with_tweets

,Unnamed: 0,Date,User ID,Tweet Count,Tweet Location,Tweet,label,city,Count
968,4036,2023-02-23,2.334396e+07,2310131,Jakarta,presiden partai keadilan sejahtera pks ahmad s...,Positive,Jakarta,23
949,3993,2023-02-23,2.334396e+07,2310131,Jakarta,pks resmi deklarasi anies baswedan sebagai baa...,Negative,Jakarta,23
1433,6118,2023-02-02,2.334396e+07,2310131,Jakarta,anies dan ganjar diprediksi melaju ke putaran ...,Negative,Jakarta,23
776,3351,2023-03-02,2.334396e+07,2310131,Jakarta,ketua umum partai demokrat agus harimurti yudh...,Positive,Jakarta,23
841,3645,2023-02-26,2.334396e+07,2310131,Jakarta,berjuang dengan keras cerdas ikhlas dan tuntas...,Positive,Jakarta,23
...,...,...,...,...,...,...,...,...,...
817,3545,2023-02-27,3.240564e+09,3,"DKI Jakarta, Indonesia",anies baswedan menuju jika jadi presiden repub...,Positive,DKI Jakarta,2
5307,6358,2023-02-01,1.891952e+09,3,NaN,ganjar pranowopresiden indonesia,Positive,NaN,2
3351,7558,2023-01-21,3.549541e+08,2,"Indramayu, Indonesia",gerindra berdiri di kaki sendiri ini sudah di ...,Positive,Indramayu,1
4036,1047,2023-03-30,4.667231e+08,2,NaN,baru tau sifat ganjar sebenarmya oh ini calon ...,Positive,NaN,2
4648,3608,2023-02-27,3.793530e+09,1,NaN,kawan ganjar sumatera utara siap mendukung pen...,Positive,NaN,2

In [26]:

df_pos = df[df['label']=='Positive']
df_positive = df[df['label']=='Positive']
df_positive = df_positive.groupby('User ID').size().nlargest(10).reset_index(name='Count')
df_positive = pd.DataFrame(df_positive)
df_positive = pd.merge(df_positive, df_pos, on='User ID')
df_positive.to_csv('positive.csv')
df_positive

# user_positive = positive_df['User ID'].value_counts()

# df_positive = df.merge(user_positive.rename('Count'), left_on='User ID', right_index=True)

# df_positive = df_positive.sort_values(by='Count', ascending=False)

,User ID,Count,Unnamed: 0,Date,Tweet Count,Tweet Location,Tweet,label,city
0,306615832.0,296,678,2023-04-07,7501,NaN,asmara anies pemimpin pro rakyat presiden ri,Positive,NaN
1,306615832.0,296,679,2023-04-07,7501,NaN,anies pemimpin pro rakyat presiden ri,Positive,NaN
2,306615832.0,296,683,2023-04-07,7501,NaN,anies pemimpin pro rakyat presiden ri,Positive,NaN
3,306615832.0,296,688,2023-04-07,7501,NaN,anies pemimpin bersih jujur dan cerdas saatnya...,Positive,NaN
4,306615832.0,296,691,2023-04-07,7501,NaN,anies pemimpin pro rakyat presiden ri,Positive,NaN
...,...,...,...,...,...,...,...,...,...
843,69183155.0,42,6348,2023-02-01,8,biawak,dari hobi terus bangun kesolidan untuk dukunga...,Positive,biawak
844,69183155.0,42,6520,2023-01-31,1473,"Beji, Indonesia",kita harus terus semangat dalam mendukung pak ...,Positive,Beji
845,69183155.0,42,6521,2023-01-31,16764,Indonesia,susunan capres yg saya dukung dari tahun sampa...,Positive,Indonesia
846,69183155.0,42,8549,2023-01-17,137121,"Tangerang, Banten",paguyuban nelayan sinar bahari semarang deklar...,Positive,Tangerang
847,69183155.0,42,9859,2023-01-07,7682,"Jawa Tengah, Indonesia",hari ini seluruh organ relawan ganjar pranowo ...,Positive,Jawa Tengah

In [28]:

df_neg = df[df['label']=='Negative']
df_negative = df[df['label']=='Negative']
df_negative = df_negative.groupby('User ID').size().nlargest(10).reset_index(name='Count')
df_negative = pd.DataFrame(df_negative)
df_negative = pd.merge(df_negative, df_neg, on='User ID')
df_negative.to_csv('negative.csv')
df_negative

# user_Negative = Negative_df['User ID'].value_counts()

# df_negative = df.merge(user_Negative.rename('Count'), left_on='User ID', right_index=True)

# df_negative = df_negative.sort_values(by='Count', ascending=False)

,User ID,Count,Unnamed: 0,Date,Tweet Count,Tweet Location,Tweet,label,city
0,3.066158e+08,76,163,2023-04-13,7501,NaN,prabowo puan vs anies khofifah siapa jadi pres...,Negative,NaN
1,3.066158e+08,76,853,2023-04-04,7501,NaN,prabowo airlangga vs anies khofifah siapa jadi...,Negative,NaN
2,3.066158e+08,76,1539,2023-03-23,7501,NaN,bersama nu anies presiden ri,Negative,NaN
3,3.066158e+08,76,1540,2023-03-23,7501,NaN,bersama nu anies presiden ri,Negative,NaN
4,3.066158e+08,76,1625,2023-03-22,7501,NaN,indonesia jaya nu jaya anies presiden ri,Negative,NaN
...,...,...,...,...,...,...,...,...,...
345,3.306055e+09,17,4098,2023-03-08,13730,San Andreas,kendati demikian koalisi ini belum menetapkan ...,Negative,San Andreas
346,3.306055e+09,17,4284,2023-03-06,13730,San Andreas,kendati demikian koalisi ini belum menetapkan ...,Negative,San Andreas
347,3.306055e+09,17,6552,2023-02-02,13730,San Andreas,dari suara para ketua pedagang pasar dan umkm ...,Negative,San Andreas
348,3.306055e+09,17,6597,2023-02-02,13730,San Andreas,gerindra pastikan prabowo akan lanjut proyek i...,Negative,San Andreas
349,3.306055e+09,17,249,2023-04-12,123279,NaN,psi merapat ke koalisi besar bersama golkar pp...,Negative,NaN